server:
  port: 8080

spring:
  profiles:
    active: local  # Activates application-local.yml

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework: INFO

invoice:
  reminder:
    schedule: "0 0 0 * * *"  # everyday at midnight
